<?php
/**
 * OpenDLP Reporter - index.phtml.
 * User: simonbeattie
 * Date: 15/07/2014
 * Time: 12:14
 */

include(__DIR__ . '/../includes/menuHeader.phtml');


echo '
            <div class="results>
            <h2>Details</h2>
            <p>Showing matches for ' . $file . '</p>

            <p><a class="myButton2" href="/results?tracker=' . $tracker . '&total='.$total.'&page='.$page.'">Back</a></p>
            <table>
            <tr>
                <th>Type</th>
                <th>Pattern</th>
                <th>Offset</th>
            </tr>

            ';


foreach ($details as $detail)
{
    echo'
                <tr>
                    <td>'.$detail['type'].'</td>
                    <td>'.$detail['pattern'].'</td>
                    <td>'.$detail['offset'].'</td>
                </tr>
    ';
}

echo '
            </table>
            </div>
    ';

include(__DIR__ . '/../includes/footer.phtml');