<?php
/**
 * OpenDLP Reporter - index.phtml.
 * User: simonbeattie
 * Date: 15/07/2014
 * Time: 12:14
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
            <div class="results">
            <h2>Systems Scanned</h2>
            <form  action="/reports" method="post" >
            <p><input class="myButton2" type="submit" value="Mark False Positive">

            ';

if (isset($success))
{
    echo '<div id="success">Successfully marked false positive</div>';
}
elseif (isset($failed))
{
    echo '<div id="failed">Failed to mark false positive</div>';
}


echo'
            </p>
            <table>
            <tr>
                <th>Select</th>
                <th>System Name</th>
                <th>Files Found</th>
                <th>Files Scanned</th>
                <th>Total Bytes Scanned</th>
                <th>Affected Files</th>

            </tr>

            ';


foreach ($systems as $system)
{
    if ($system['resultCount'] == 0)
    {
        $link = '<td><a class="myButton2" href ="#">No Results</td>';
    }
    else
    {
        $link = '<td><a class="myButton2" href ="/results?tracker='.$system['tracker'].'&total='.ceil($system['resultCount']/250).'&page=1">View</td>';
    }
    echo'
                <tr>
                    <td><input type="checkbox" name="falsepositive[]" value="'.$system['tracker'].'">
                    <td>'.$system['host_name'].'</td>
                    <td>'.$system['filestotal'].'</td>
                    <td>'.$system['filesscanned'].'</td>
                    <td>'.$system['bytesscanned'].'</td>
                    <td>'.$system['resultCount'].'</td>
                    '.$link.'
                </tr>
    ';
}

echo '

            </table>
            </form>
            </div>
    ';

include(__DIR__ . '/../includes/footer.phtml');