<?php
/**
 * StormRecon - editProfile.phtml.
 * User: simonbeattie
 * Date: 03/07/2014
 * Time: 13:18
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
<p class="header">Profiles</p>

<div class="profilesFormContainer">
    <ul class="profilesForm">
    <form method="post" action="/regex">

        <li>
            <label>Regex Name</label>
            <input type="text" name="name" value="">
        </li>
        <li>
            <label>Pattern</label>
            <input type="text" name="pattern" value="">
        </li>

<input type="submit" value="Submit">
</form>
<form method="get" action="/">
<input type="submit" value="Back">
</form>
</ul>

</div>';

include(__DIR__ . '/../includes/footer.phtml');