<?php
/**
 * OpenDLP Reporter - index.phtml.
 * User: simonbeattie
 * Date: 15/07/2014
 * Time: 12:14
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

exec("ps aux | grep -i 'agent_worker.php' | grep -v grep", $pids);

echo '
            <head><meta http-equiv="refresh" content="5" ></head>
            <div class="results">
            <h2>Current Scans</h2>

            ';

if(empty($pids)) {
    echo '<img src="/images/cross.png">Agent Worker Not Running!';
} else {
    echo '<img src="/images/tick.png">Agent Worker Running';
}


echo'
            </p>
            <table>
            <tr>

                <th>System Name</th>
                <th>Files Found</th>
                <th>Files Scanned</th>
                <th>Bytes Founds</th>
                <th>Bytes Scanned</th>
                <th>Scan Started</th>
                <th>Status</th>

            </tr>

            ';


foreach ($currentScans as $system)
{

    if ($system['status'] == 'Scanning')
    {
        $status = 'Scanning <img width="15" height="15" src="/images/spinner3-black.gif" >';
    } else {
        $status = $system['status'];
    }

    echo'
                <tr>
                    <td>'.$system['host_name'].'</td>
                    <td>'.number_format($system['filestotal']).'</td>
                    <td>'.number_format($system['filesscanned']).'</td>
                    <td>'.number_format($system['bytestotal']).'</td>
                    <td>'.number_format($system['bytesscanned']).'</td>
                    <td>'.$system['start_time'].'</td>
                    <td>'.$status.'</td>
                </tr>
    ';
}

echo '

            </table>

            </div>
    ';

include(__DIR__ . '/../includes/footer.phtml');