<?php
/**
 * OpenDLP Reporter - index.phtml.
 * User: simonbeattie
 * Date: 15/07/2014
 * Time: 12:14
 */

include(__DIR__ . '/../includes/menuHeader.phtml');

echo '
            <div class="results">
            ';



echo'
            </p>
            <table>
            <tr>

                <th>System Name</th>
                <th>Files Found</th>
                <th>Files Scanned</th>
                <th>Bytes Founds</th>
                <th>Bytes Scanned</th>
                <th>Scan Started</th>
                <th>Status</th>

            </tr>

            ';


foreach ($currentScans as $system)
{

    if ($system['status'] == 3)
    {
        $status = '<img width="20" height="20" src="/images/spinner3-black.gif" >';
    } else {
        $status = $system['status'];
    }

    echo'
                <tr>
                    <td>'.$system['host_name'].'</td>
                    <td>'.number_format($system['filestotal']).'</td>
                    <td>'.number_format($system['filesscanned']).'</td>
                    <td>'.number_format($system['bytestotal']).'</td>
                    <td>'.number_format($system['bytesscanned']).'</td>
                    <td>'.$system['start_time'].'</td>
                    <td>'.$status.'</td>
                </tr>
    ';
}

echo '

            </table>

            </div>
    ';

include(__DIR__ . '/../includes/footer.phtml');